# Generated by Django 5.1.4 on 2025-01-02 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Doctorname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('T', 'Transgender')], max_length=2)),
                ('DOB', models.DateField()),
                ('number', models.IntegerField(unique=True)),
                ('Medical_Degree', models.CharField(max_length=100)),
                ('University_Name', models.CharField(max_length=100)),
                ('Graduation_Year', models.IntegerField()),
                ('Specialty', models.CharField(max_length=100)),
                ('Address', models.TextField(max_length=500)),
                ('Photo', models.ImageField(upload_to='profile_image/')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('T', 'Transgender')], max_length=2)),
                ('DOB', models.DateField()),
                ('number', models.IntegerField(unique=True)),
            ],
        ),
    ]
