# Generated by Django 5.1.4 on 2025-01-02 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='Photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_image/'),
        ),
    ]
